version: '3'
services:
  app:
    container_name: app
    image: 127.0.0.1:4005/stackdemo
    restart: always
    build: .
    ports:
      - '4000:4000'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
